---
version: '3'
services:
  frontend:
    container_name: cth_frontend
    build:
      context: ../
      dockerfile: Dockerfile
    image: cth_frontend:latest
    environment:
      NODE_ENV: 'development'
      BACKEND_URL: 'http://54.215.249.143'
    ports:
      # localhost:container
      - '3000:8080'