export const countries = [
  { code: "AD", label: "Andorra", phone: "376" },
  { code: "AE", label: "United Arab Emirates", phone: "971" },
  { code: "AF", label: "Afghanistan", phone: "93" },
  { code: "AG", label: "Antigua and Barbuda", phone: "1-268" },
  { code: "AI", label: "Anguilla", phone: "1-264" },
  { code: "AL", label: "Albania", phone: "355" },
  { code: "AM", label: "Armenia", phone: "374" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "AQ", label: "Antarctica", phone: "672" },
  { code: "AR", label: "Argentina", phone: "54" },
  { code: "AS", label: "American Samoa", phone: "1-684" },
  { code: "AT", label: "Austria", phone: "43" },
  { code: "AU", label: "Australia", phone: "61", suggested: true },
  { code: "AW", label: "Aruba", phone: "297" },
  { code: "AX", label: "Alland Islands", phone: "358" },
  { code: "AZ", label: "Azerbaijan", phone: "994" },
  { code: "BA", label: "Bosnia and Herzegovina", phone: "387" },
  { code: "BB", label: "Barbados", phone: "1-246" },
  { code: "BD", label: "Bangladesh", phone: "880" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "BG", label: "Bulgaria", phone: "359" },
  { code: "BH", label: "Bahrain", phone: "973" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "BJ", label: "Benin", phone: "229" },
  { code: "BL", label: "Saint Barthelemy", phone: "590" },
  { code: "BM", label: "Bermuda", phone: "1-441" },
  { code: "BN", label: "Brunei Darussalam", phone: "673" },
  { code: "BO", label: "Bolivia", phone: "591" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "BS", label: "Bahamas", phone: "1-242" },
  { code: "BT", label: "Bhutan", phone: "975" },
  { code: "BV", label: "Bouvet Island", phone: "47" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "BY", label: "Belarus", phone: "375" },
  { code: "BZ", label: "Belize", phone: "501" },
  { code: "CA", label: "Canada", phone: "1", suggested: true },
  { code: "CC", label: "Cocos (Keeling) Islands", phone: "61" },
  { code: "CD", label: "Congo, Democratic Republic of the", phone: "243" },
  { code: "CF", label: "Central African Republic", phone: "236" },
  { code: "CG", label: "Congo, Republic of the", phone: "242" },
  { code: "CH", label: "Switzerland", phone: "41" },
  { code: "CI", label: "Cote d'Ivoire", phone: "225" },
  { code: "CK", label: "Cook Islands", phone: "682" },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CM", label: "Cameroon", phone: "237" },
  { code: "CN", label: "China", phone: "86" },
  { code: "CO", label: "Colombia", phone: "57" },
  { code: "CR", label: "Costa Rica", phone: "506" },
  { code: "CU", label: "Cuba", phone: "53" },
  { code: "CV", label: "Cape Verde", phone: "238" },
  { code: "CW", label: "Curacao", phone: "599" },
  { code: "CX", label: "Christmas Island", phone: "61" },
  { code: "CY", label: "Cyprus", phone: "357" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  { code: "DE", label: "Germany", phone: "49", suggested: true },
  { code: "DJ", label: "Djibouti", phone: "253" },
  { code: "DK", label: "Denmark", phone: "45" },
  { code: "DM", label: "Dominica", phone: "1-767" },
  { code: "DO", label: "Dominican Republic", phone: "1-809" },
  { code: "DZ", label: "Algeria", phone: "213" },
  { code: "EC", label: "Ecuador", phone: "593" },
  { code: "EE", label: "Estonia", phone: "372" },
  { code: "EG", label: "Egypt", phone: "20" },
  { code: "EH", label: "Western Sahara", phone: "212" },
  { code: "ER", label: "Eritrea", phone: "291" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "ET", label: "Ethiopia", phone: "251" },
  { code: "FI", label: "Finland", phone: "358" },
  { code: "FJ", label: "Fiji", phone: "679" },
  { code: "FK", label: "Falkland Islands (Malvinas)", phone: "500" },
  { code: "FM", label: "Micronesia, Federated States of", phone: "691" },
  { code: "FO", label: "Faroe Islands", phone: "298" },
  { code: "FR", label: "France", phone: "33", suggested: true },
  { code: "GA", label: "Gabon", phone: "241" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  { code: "GD", label: "Grenada", phone: "1-473" },
  { code: "GE", label: "Georgia", phone: "995" },
  { code: "GF", label: "French Guiana", phone: "594" },
  { code: "GG", label: "Guernsey", phone: "44" },
  { code: "GH", label: "Ghana", phone: "233" },
  { code: "GI", label: "Gibraltar", phone: "350" },
  { code: "GL", label: "Greenland", phone: "299" },
  { code: "GM", label: "Gambia", phone: "220" },
  { code: "GN", label: "Guinea", phone: "224" },
  { code: "GP", label: "Guadeloupe", phone: "590" },
  { code: "GQ", label: "Equatorial Guinea", phone: "240" },
  { code: "GR", label: "Greece", phone: "30" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", label: "Guatemala", phone: "502" },
  { code: "GU", label: "Guam", phone: "1-671" },
  { code: "GW", label: "Guinea-Bissau", phone: "245" },
  { code: "GY", label: "Guyana", phone: "592" },
  { code: "HK", label: "Hong Kong", phone: "852" },
  { code: "HM", label: "Heard Island and McDonald Islands", phone: "672" },
  { code: "HN", label: "Honduras", phone: "504" },
  { code: "HR", label: "Croatia", phone: "385" },
  { code: "HT", label: "Haiti", phone: "509" },
  { code: "HU", label: "Hungary", phone: "36" },
  { code: "ID", label: "Indonesia", phone: "62" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "IL", label: "Israel", phone: "972" },
  { code: "IM", label: "Isle of Man", phone: "44" },
  { code: "IN", label: "India", phone: "91" },
  { code: "IO", label: "British Indian Ocean Territory", phone: "246" },
  { code: "IQ", label: "Iraq", phone: "964" },
  { code: "IR", label: "Iran, Islamic Republic of", phone: "98" },
  { code: "IS", label: "Iceland", phone: "354" },
  { code: "IT", label: "Italy", phone: "39" },
  { code: "JE", label: "Jersey", phone: "44" },
  { code: "JM", label: "Jamaica", phone: "1-876" },
  { code: "JO", label: "Jordan", phone: "962" },
  { code: "JP", label: "Japan", phone: "81", suggested: true },
  { code: "KE", label: "Kenya", phone: "254" },
  { code: "KG", label: "Kyrgyzstan", phone: "996" },
  { code: "KH", label: "Cambodia", phone: "855" },
  { code: "KI", label: "Kiribati", phone: "686" },
  { code: "KM", label: "Comoros", phone: "269" },
  { code: "KN", label: "Saint Kitts and Nevis", phone: "1-869" },
  { code: "KP", label: "Korea, Democratic People's Republic of", phone: "850" },
  { code: "KR", label: "Korea, Republic of", phone: "82" },
  { code: "KW", label: "Kuwait", phone: "965" },
  { code: "KY", label: "Cayman Islands", phone: "1-345" },
  { code: "KZ", label: "Kazakhstan", phone: "7" },
  { code: "LA", label: "Lao People's Democratic Republic", phone: "856" },
  { code: "LB", label: "Lebanon", phone: "961" },
  { code: "LC", label: "Saint Lucia", phone: "1-758" },
  { code: "LI", label: "Liechtenstein", phone: "423" },
  { code: "LK", label: "Sri Lanka", phone: "94" },
  { code: "LR", label: "Liberia", phone: "231" },
  { code: "LS", label: "Lesotho", phone: "266" },
  { code: "LT", label: "Lithuania", phone: "370" },
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "LV", label: "Latvia", phone: "371" },
  { code: "LY", label: "Libya", phone: "218" },
  { code: "MA", label: "Morocco", phone: "212" },
  { code: "MC", label: "Monaco", phone: "377" },
  { code: "MD", label: "Moldova, Republic of", phone: "373" },
  { code: "ME", label: "Montenegro", phone: "382" },
  { code: "MF", label: "Saint Martin (French part)", phone: "590" },
  { code: "MG", label: "Madagascar", phone: "261" },
  { code: "MH", label: "Marshall Islands", phone: "692" },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", label: "Mali", phone: "223" },
  { code: "MM", label: "Myanmar", phone: "95" },
  { code: "MN", label: "Mongolia", phone: "976" },
  { code: "MO", label: "Macao", phone: "853" },
  { code: "MP", label: "Northern Mariana Islands", phone: "1-670" },
  { code: "MQ", label: "Martinique", phone: "596" },
  { code: "MR", label: "Mauritania", phone: "222" },
  { code: "MS", label: "Montserrat", phone: "1-664" },
  { code: "MT", label: "Malta", phone: "356" },
  { code: "MU", label: "Mauritius", phone: "230" },
  { code: "MV", label: "Maldives", phone: "960" },
  { code: "MW", label: "Malawi", phone: "265" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "MY", label: "Malaysia", phone: "60" },
  { code: "MZ", label: "Mozambique", phone: "258" },
  { code: "NA", label: "Namibia", phone: "264" },
  { code: "NC", label: "New Caledonia", phone: "687" },
  { code: "NE", label: "Niger", phone: "227" },
  { code: "NF", label: "Norfolk Island", phone: "672" },
  { code: "NG", label: "Nigeria", phone: "234" },
  { code: "NI", label: "Nicaragua", phone: "505" },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "NO", label: "Norway", phone: "47" },
  { code: "NP", label: "Nepal", phone: "977" },
  { code: "NR", label: "Nauru", phone: "674" },
  { code: "NU", label: "Niue", phone: "683" },
  { code: "NZ", label: "New Zealand", phone: "64" },
  { code: "OM", label: "Oman", phone: "968" },
  { code: "PA", label: "Panama", phone: "507" },
  { code: "PE", label: "Peru", phone: "51" },
  { code: "PF", label: "French Polynesia", phone: "689" },
  { code: "PG", label: "Papua New Guinea", phone: "675" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "PK", label: "Pakistan", phone: "92" },
  { code: "PL", label: "Poland", phone: "48" },
  { code: "PM", label: "Saint Pierre and Miquelon", phone: "508" },
  { code: "PN", label: "Pitcairn", phone: "870" },
  { code: "PR", label: "Puerto Rico", phone: "1" },
  { code: "PS", label: "Palestine, State of", phone: "970" },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "PW", label: "Palau", phone: "680" },
  { code: "PY", label: "Paraguay", phone: "595" },
  { code: "QA", label: "Qatar", phone: "974" },
  { code: "RE", label: "Reunion", phone: "262" },
  { code: "RO", label: "Romania", phone: "40" },
  { code: "RS", label: "Serbia", phone: "381" },
  { code: "RU", label: "Russian Federation", phone: "7" },
  { code: "RW", label: "Rwanda", phone: "250" },
  { code: "SA", label: "Saudi Arabia", phone: "966" },
  { code: "SB", label: "Solomon Islands", phone: "677" },
  { code: "SC", label: "Seychelles", phone: "248" },
  { code: "SD", label: "Sudan", phone: "249" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "SG", label: "Singapore", phone: "65" },
  { code: "SH", label: "Saint Helena", phone: "290" },
  { code: "SI", label: "Slovenia", phone: "386" },
  { code: "SJ", label: "Svalbard and Jan Mayen", phone: "47" },
  { code: "SK", label: "Slovakia", phone: "421" },
  { code: "SL", label: "Sierra Leone", phone: "232" },
  { code: "SM", label: "San Marino", phone: "378" },
  { code: "SN", label: "Senegal", phone: "221" },
  { code: "SO", label: "Somalia", phone: "252" },
  { code: "SR", label: "Suriname", phone: "597" },
  { code: "SS", label: "South Sudan", phone: "211" },
  { code: "ST", label: "Sao Tome and Principe", phone: "239" },
  { code: "SV", label: "El Salvador", phone: "503" },
  { code: "SX", label: "Sint Maarten (Dutch part)", phone: "1-721" },
  { code: "SY", label: "Syrian Arab Republic", phone: "963" },
  { code: "SZ", label: "Swaziland", phone: "268" },
  { code: "TC", label: "Turks and Caicos Islands", phone: "1-649" },
  { code: "TD", label: "Chad", phone: "235" },
  { code: "TF", label: "French Southern Territories", phone: "262" },
  { code: "TG", label: "Togo", phone: "228" },
  { code: "TH", label: "Thailand", phone: "66" },
  { code: "TJ", label: "Tajikistan", phone: "992" },
  { code: "TK", label: "Tokelau", phone: "690" },
  { code: "TL", label: "Timor-Leste", phone: "670" },
  { code: "TM", label: "Turkmenistan", phone: "993" },
  { code: "TN", label: "Tunisia", phone: "216" },
  { code: "TO", label: "Tonga", phone: "676" },
  { code: "TR", label: "Turkey", phone: "90" },
  { code: "TT", label: "Trinidad and Tobago", phone: "1-868" },
  { code: "TV", label: "Tuvalu", phone: "688" },
  { code: "TW", label: "Taiwan, Province of China", phone: "886" },
  { code: "TZ", label: "United Republic of Tanzania", phone: "255" },
  { code: "UA", label: "Ukraine", phone: "380" },
  { code: "UG", label: "Uganda", phone: "256" },
  { code: "US", label: "United States", phone: "1", suggested: true },
  { code: "UY", label: "Uruguay", phone: "598" },
  { code: "UZ", label: "Uzbekistan", phone: "998" },
  { code: "VA", label: "Holy See (Vatican City State)", phone: "379" },
  { code: "VC", label: "Saint Vincent and the Grenadines", phone: "1-784" },
  { code: "VE", label: "Venezuela", phone: "58" },
  { code: "VG", label: "British Virgin Islands", phone: "1-284" },
  { code: "VI", label: "US Virgin Islands", phone: "1-340" },
  { code: "VN", label: "Vietnam", phone: "84" },
  { code: "VU", label: "Vanuatu", phone: "678" },
  { code: "WF", label: "Wallis and Futuna", phone: "681" },
  { code: "WS", label: "Samoa", phone: "685" },
  { code: "XK", label: "Kosovo", phone: "383" },
  { code: "YE", label: "Yemen", phone: "967" },
  { code: "YT", label: "Mayotte", phone: "262" },
  { code: "ZA", label: "South Africa", phone: "27" },
  { code: "ZM", label: "Zambia", phone: "260" },
  { code: "ZW", label: "Zimbabwe", phone: "263" },
];

export const sectors = [
  { sector: "advertising" },
  { sector: "agriculture" },
  { sector: "biology" },
  { sector: "biotech" },
  { sector: "broadcasting" },
  { sector: "bureaucracy" },
  { sector: "central bank" },
  { sector: "community and lifestyle" },
  { sector: "content and publishing" },
  { sector: "cryptocurrency" },
  { sector: "cyber security" },
  { sector: "data/information" },
  { sector: "distribution" },
  { sector: "educations" },
  { sector: "email marketing" },
  { sector: "financial services" },
  { sector: "government" },
  { sector: "healthcare" },
  { sector: "human resources" },
  { sector: "information services" },
  { sector: "information technology" },
  { sector: "internet services" },
  { sector: "law enforcement" },
  { sector: "lending and investments" },
  { sector: "manufacturing" },
  { sector: "media & entertainment" },
  { sector: "medical" },
  { sector: "military" },
  { sector: "mutual aid" },
  { sector: "national security" },
  { sector: "news" },
  { sector: "pharmaceuticals" },
  { sector: "politics" },
  { sector: "privacy and security" },
  { sector: "public administration" },
  { sector: "public safety" },
  { sector: "regulation" },
  { sector: "research" },
  { sector: "sales and marketing" },
  { sector: "supply" },
  { sector: "support" },
];

export const roles = [
  { role: "Chief Executives" },
  { role: "General and Operations Managers" },
  { role: "Legislators" },
  { role: "Advertising and Promotions Managers" },
  { role: "Marketing and Sales Managers" },
  { role: "Marketing Managers" },
  { role: "Sales Managers" },
  { role: "Public Relations and Fundraising Managers" },
  { role: "Public Relations Managers" },
  { role: "Fundraising Managers" },
  { role: "Administrative Services and Facilities Managers" },
  { role: "Administrative Services Managers" },
  { role: "Facilities Managers" },
  { role: "Computer and Information Systems Managers" },
  { role: "Financial Managers" },
  { role: "Industrial Production Managers" },
  { role: "Purchasing Managers" },
  { role: "Transportation, Storage, and Distribution Managers" },
  { role: "Compensation and Benefits Managers" },
  { role: "Human Resources Managers" },
  { role: "Training and Development Managers" },
  { role: "Farmers, Ranchers, and Other Agricultural Managers" },
  { role: "Construction Managers" },
  { role: "Education and Childcare Administrators" },
  { role: "Education and Childcare Administrators, Preschool and Daycare" },
  { role: "Education Administrators, Kindergarten through Secondary" },
  { role: "Education Administrators, Postsecondary" },
  { role: "Education Administrators, All Other" },
  { role: "Architectural and Engineering Managers" },
  { role: "Food Service Managers" },
  { role: "Entertainment and Recreation Managers" },
  { role: "Gambling Managers" },
  { role: "Entertainment and Recreation Managers, Except Gambling" },
  { role: "Lodging Managers" },
  { role: "Medical and Health Services Managers" },
  { role: "Natural Sciences Managers" },
  { role: "Postmasters and Mail Superintendents" },
  { role: "Property, Real Estate, and Community Association Managers" },
  { role: "Social and Community Service Managers" },
  { role: "Emergency Management Directors" },
  { role: "Personal Service Managers" },
  { role: "Funeral Home Managers" },
  { role: "Personal Service Managers, All Other" },
  { role: "Miscellaneous Managers" },
  { role: "Managers, All Other" },
  { role: "Agents and Business Managers of Artists, Performers, and Athletes" },
  { role: "Buyers and Purchasing Agents" },
  { role: "Buyers and Purchasing Agents, Farm Products" },
  { role: "Wholesale and Retail Buyers, Except Farm Products" },
  { role: "Purchasing Agents, Except Wholesale, Retail, and Farm Products" },
  { role: "Claims Adjusters, Appraisers, Examiners, and Investigators" },
  { role: "Claims Adjusters, Examiners, and Investigators" },
  { role: "Insurance Appraisers, Auto Damage" },
  { role: "Compliance Officers" },
  { role: "Cost Estimators" },
  { role: "Human Resources Workers" },
  { role: "Human Resources Specialists" },
  { role: "Farm Labor Contractors" },
  { role: "Labor Relations Specialists" },
  { role: "Logisticians and Project Management Specialists" },
  { role: "Logisticians" },
  { role: "Project Management Specialists" },
  { role: "Management Analysts" },
  { role: "Meeting, Convention, and Event Planners" },
  { role: "Fundraisers" },
  { role: "Compensation, Benefits, and Job Analysis Specialists" },
  { role: "Training and Development Specialists" },
  { role: "Market Research Analysts and Marketing Specialists" },
  { role: "Miscellaneous Business Operations Specialists" },
  { role: "Business Operations Specialists, All Other" },
  { role: "Accountants and Auditors" },
  { role: "Property Appraisers and Assessors" },
  { role: "Appraisers of Personal and Business Property" },
  { role: "Appraisers and Assessors of Real Estate" },
  { role: "Budget Analysts" },
  { role: "Credit Analysts" },
  { role: "Financial Analysts and Advisors" },
  { role: "Financial and Investment Analysts" },
  { role: "Personal Financial Advisors" },
  { role: "Insurance Underwriters" },
  { role: "Financial Risk Specialists" },
  { role: "Financial Examiners" },
  { role: "Credit Counselors and Loan Officers" },
  { role: "Credit Counselors" },
  { role: "Loan Officers" },
  { role: "Tax Examiners, Collectors and Preparers, and Revenue Agents" },
  { role: "Tax Examiners and Collectors, and Revenue Agents" },
  { role: "Tax Preparers" },
  { role: "Miscellaneous Financial Specialists" },
  { role: "Financial Specialists, All Other" },
  { role: "Computer and Information Analysts" },
  { role: "Computer Systems Analysts" },
  { role: "Information Security Analysts" },
  { role: "Computer and Information Research Scientists" },
  { role: "Computer Support Specialists" },
  { role: "Computer Network Support Specialists" },
  { role: "Computer User Support Specialists" },
  { role: "Database and Network Administrators and Architects" },
  { role: "Computer Network Architects" },
  { role: "Database Administrators" },
  { role: "Database Architects" },
  { role: "Network and Computer Systems Administrators" },
  { role: "Software and Web Developers, Programmers, and Testers" },
  { role: "Computer Programmers" },
  { role: "Software Developers" },
  { role: "Software Quality Assurance Analysts and Testers" },
  { role: "Web Developers" },
  { role: "Web and Digital Interface Designers" },
  { role: "Miscellaneous Computer Occupations" },
  { role: "Computer Occupations, All Other" },
  { role: "Actuaries" },
  { role: "Mathematicians" },
  { role: "Operations Research Analysts" },
  { role: "Statisticians" },
  { role: "Data Scientists" },
  { role: "Miscellaneous Mathematical Science Occupations" },
  { role: "Mathematical Science Occupations, All Other" },
  { role: "Architects, Except Naval" },
  { role: "Architects, Except Landscape and Naval" },
  { role: "Landscape Architects" },
  { role: "Surveyors, Cartographers, and Photogrammetrists" },
  { role: "Cartographers and Photogrammetrists" },
  { role: "Surveyors" },
  { role: "Aerospace Engineers" },
  { role: "Agricultural Engineers" },
  { role: "Bioengineers and Biomedical Engineers" },
  { role: "Chemical Engineers" },
  { role: "Civil Engineers" },
  { role: "Computer Hardware Engineers" },
  { role: "Electrical and Electronics Engineers" },
  { role: "Electrical Engineers" },
  { role: "Electronics Engineers, Except Computer" },
  { role: "Environmental Engineers" },
  { role: "Industrial Engineers, Including Health and Safety" },
  {
    role:
      "Health and Safety Engineers, Except Mining Safety Engineers and Inspectors",
  },
  { role: "Industrial Engineers" },
  { role: "Marine Engineers and Naval Architects" },
  { role: "Materials Engineers" },
  { role: "Mechanical Engineers" },
  {
    role: "Mining and Geological Engineers, Including Mining Safety Engineers",
  },
  { role: "Nuclear Engineers" },
  { role: "Petroleum Engineers" },
  { role: "Miscellaneous Engineers" },
  { role: "Engineers, All Other" },
  { role: "Drafters" },
  { role: "Architectural and Civil Drafters" },
  { role: "Electrical and Electronics Drafters" },
  { role: "Mechanical Drafters" },
  { role: "Drafters, All Other" },
  { role: "Engineering Technologists and Technicians, Except Drafters" },
  {
    role: "Aerospace Engineering and Operations Technologists and Technicians",
  },
  { role: "Civil Engineering Technologists and Technicians" },
  {
    role: "Electrical and Electronic Engineering Technologists and Technicians",
  },
  { role: "Electro-Mechanical and Mechatronics Technologists and Technicians" },
  { role: "Environmental Engineering Technologists and Technicians" },
  { role: "Industrial Engineering Technologists and Technicians" },
  { role: "Mechanical Engineering Technologists and Technicians" },
  { role: "Calibration Technologists and Technicians" },
  {
    role:
      "Engineering Technologists and Technicians, Except Drafters, All Other",
  },
  { role: "Surveying and Mapping Technicians" },
  { role: "Agricultural and Food Scientists" },
  { role: "Animal Scientists" },
  { role: "Food Scientists and Technologists" },
  { role: "Soil and Plant Scientists" },
  { role: "Biological Scientists" },
  { role: "Biochemists and Biophysicists" },
  { role: "Microbiologists" },
  { role: "Zoologists and Wildlife Biologists" },
  { role: "Biological Scientists, All Other" },
  { role: "Conservation Scientists and Foresters" },
  { role: "Conservation Scientists" },
  { role: "Foresters" },
  { role: "Medical Scientists" },
  { role: "Epidemiologists" },
  { role: "Medical Scientists, Except Epidemiologists" },
  { role: "Miscellaneous Life Scientists" },
  { role: "Life Scientists, All Other" },
  { role: "Astronomers and Physicists" },
  { role: "Astronomers" },
  { role: "Physicists" },
  { role: "Atmospheric and Space Scientists" },
  { role: "Chemists and Materials Scientists" },
  { role: "Chemists" },
  { role: "Materials Scientists" },
  { role: "Environmental Scientists and Geoscientists" },
  { role: "Environmental Scientists and Specialists, Including Health" },
  { role: "Geoscientists, Except Hydrologists and Geographers" },
  { role: "Hydrologists" },
  { role: "Miscellaneous Physical Scientists" },
  { role: "Physical Scientists, All Other" },
  { role: "Economists" },
  { role: "Survey Researchers" },
  { role: "Psychologists" },
  { role: "Industrial-Organizational Psychologists" },
  { role: "Clinical and Counseling Psychologists" },
  { role: "School Psychologists" },
  { role: "Psychologists, All Other" },
  { role: "Sociologists" },
  { role: "Urban and Regional Planners" },
  { role: "Miscellaneous Social Scientists and Related Workers" },
  { role: "Anthropologists and Archeologists" },
  { role: "Geographers" },
  { role: "Historians" },
  { role: "Political Scientists" },
  { role: "Social Scientists and Related Workers, All Other" },
  { role: "Agricultural and Food Science Technicians" },
  { role: "Agricultural Technicians" },
  { role: "Food Science Technicians" },
  { role: "Biological Technicians" },
  { role: "Chemical Technicians" },
  { role: "Environmental Science and Geoscience Technicians" },
  {
    role: "Environmental Science and Protection Technicians, Including Health",
  },
  { role: "Geological Technicians, Except Hydrologic Technicians" },
  { role: "Hydrologic Technicians" },
  { role: "Nuclear Technicians" },
  { role: "Social Science Research Assistants" },
  { role: "Forest and Conservation Technicians" },
  { role: "Miscellaneous Life, Physical, and Social Science Technicians" },
  { role: "Forensic Science Technicians" },
  { role: "Life, Physical, and Social Science Technicians, All Other" },
  { role: "Occupational Health and Safety Specialists and Technicians" },
  { role: "Occupational Health and Safety Specialists" },
  { role: "Occupational Health and Safety Technicians" },
  { role: "Counselors" },
  { role: "Substance Abuse and Behavioral Disorder Counselors" },
  { role: "Educational, Guidance, and Career Counselors and Advisors" },
  { role: "Marriage and Family Therapists" },
  { role: "Mental Health Counselors" },
  { role: "Rehabilitation Counselors" },
  { role: "Counselors, All Other" },
  { role: "Social Workers" },
  { role: "Child, Family, and School Social Workers" },
  { role: "Healthcare Social Workers" },
  { role: "Mental Health and Substance Abuse Social Workers" },
  { role: "Social Workers, All Other" },
  { role: "Miscellaneous Community and Social Service Specialists" },
  { role: "Health Education Specialists" },
  { role: "Probation Officers and Correctional Treatment Specialists" },
  { role: "Social and Human Service Assistants" },
  { role: "Community Health Workers" },
  { role: "Community and Social Service Specialists, All Other" },
  { role: "Clergy" },
  { role: "Directors, Religious Activities and Education" },
  { role: "Miscellaneous Religious Workers" },
  { role: "Religious Workers, All Other" },
  { role: "Lawyers and Judicial Law Clerks" },
  { role: "Lawyers" },
  { role: "Judicial Law Clerks" },
  { role: "Judges, Magistrates, and Other Judicial Workers" },
  { role: "Administrative Law Judges, Adjudicators, and Hearing Officers" },
  { role: "Arbitrators, Mediators, and Conciliators" },
  { role: "Judges, Magistrate Judges, and Magistrates" },
  { role: "Paralegals and Legal Assistants" },
  { role: "Miscellaneous Legal Support Workers" },
  { role: "Title Examiners, Abstractors, and Searchers" },
  { role: "Legal Support Workers, All Other" },
  { role: "Business Teachers, Postsecondary" },
  { role: "Math and Computer Science Teachers, Postsecondary" },
  { role: "Computer Science Teachers, Postsecondary" },
  { role: "Mathematical Science Teachers, Postsecondary" },
  { role: "Engineering and Architecture Teachers, Postsecondary" },
  { role: "Architecture Teachers, Postsecondary" },
  { role: "Engineering Teachers, Postsecondary" },
  { role: "Life Sciences Teachers, Postsecondary" },
  { role: "Agricultural Sciences Teachers, Postsecondary" },
  { role: "Biological Science Teachers, Postsecondary" },
  { role: "Forestry and Conservation Science Teachers, Postsecondary" },
  { role: "Physical Sciences Teachers, Postsecondary" },
  {
    role:
      "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",
  },
  { role: "Chemistry Teachers, Postsecondary" },
  { role: "Environmental Science Teachers, Postsecondary" },
  { role: "Physics Teachers, Postsecondary" },
  { role: "Social Sciences Teachers, Postsecondary" },
  { role: "Anthropology and Archeology Teachers, Postsecondary" },
  { role: "Area, Ethnic, and Cultural Studies Teachers, Postsecondary" },
  { role: "Economics Teachers, Postsecondary" },
  { role: "Geography Teachers, Postsecondary" },
  { role: "Political Science Teachers, Postsecondary" },
  { role: "Psychology Teachers, Postsecondary" },
  { role: "Sociology Teachers, Postsecondary" },
  { role: "Social Sciences Teachers, Postsecondary, All Other" },
  { role: "Health Teachers, Postsecondary" },
  { role: "Health Specialties Teachers, Postsecondary" },
  { role: "Nursing Instructors and Teachers, Postsecondary" },
  { role: "Education and Library Science Teachers, Postsecondary" },
  { role: "Education Teachers, Postsecondary" },
  { role: "Library Science Teachers, Postsecondary" },
  { role: "Law, Criminal Justice, and Social Work Teachers, Postsecondary" },
  { role: "Criminal Justice and Law Enforcement Teachers, Postsecondary" },
  { role: "Law Teachers, Postsecondary" },
  { role: "Social Work Teachers, Postsecondary" },
  {
    role:
      "Arts, Communications, History, and Humanities Teachers, Postsecondary",
  },
  { role: "Art, Drama, and Music Teachers, Postsecondary" },
  { role: "Communications Teachers, Postsecondary" },
  { role: "English Language and Literature Teachers, Postsecondary" },
  { role: "Foreign Language and Literature Teachers, Postsecondary" },
  { role: "History Teachers, Postsecondary" },
  { role: "Philosophy and Religion Teachers, Postsecondary" },
  { role: "Miscellaneous Postsecondary Teachers" },
  { role: "Family and Consumer Sciences Teachers, Postsecondary" },
  { role: "Recreation and Fitness Studies Teachers, Postsecondary" },
  { role: "Career/Technical Education Teachers, Postsecondary" },
  { role: "Postsecondary Teachers, All Other" },
  { role: "Preschool and Kindergarten Teachers" },
  { role: "Preschool Teachers, Except Special Education" },
  { role: "Kindergarten Teachers, Except Special Education" },
  { role: "Elementary and Middle School Teachers" },
  { role: "Elementary School Teachers, Except Special Education" },
  {
    role:
      "Middle School Teachers, Except Special and Career/Technical Education",
  },
  { role: "Career/Technical Education Teachers, Middle School" },
  { role: "Secondary School Teachers" },
  {
    role:
      "Secondary School Teachers, Except Special and Career/Technical Education",
  },
  { role: "Career/Technical Education Teachers, Secondary School" },
  { role: "Special Education Teachers" },
  { role: "Special Education Teachers, Preschool" },
  { role: "Special Education Teachers, Kindergarten" },
  { role: "Special Education Teachers, Elementary School" },
  { role: "Special Education Teachers, Middle School" },
  { role: "Special Education Teachers, Secondary School" },
  { role: "Special Education Teachers, All Other" },
  {
    role:
      "Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors",
  },
  { role: "Self-Enrichment Teachers" },
  { role: "Substitute Teachers, Short-Term" },
  { role: "Tutors" },
  { role: "Miscellaneous Teachers and Instructors" },
  { role: "Teachers and Instructors, All Other" },
  { role: "Archivists, Curators, and Museum Technicians" },
  { role: "Archivists" },
  { role: "Curators" },
  { role: "Museum Technicians and Conservators" },
  { role: "Librarians and Media Collections Specialists" },
  { role: "Library Technicians" },
  { role: "Farm and Home Management Educators" },
  { role: "Instructional Coordinators" },
  { role: "Teaching Assistants" },
  {
    role:
      "Teaching Assistants, Preschool, Elementary, Middle, and Secondary School, Except Special Education",
  },
  { role: "Teaching Assistants, Special Education" },
  { role: "Teaching Assistants, Postsecondary" },
  { role: "Teaching Assistants, All Other" },
  { role: "Miscellaneous Educational Instruction and Library Workers" },
  { role: "Educational Instruction and Library Workers, All Other" },
  { role: "Artists and Related Workers" },
  { role: "Art Directors" },
  { role: "Craft Artists" },
  { role: "Fine Artists, Including Painters, Sculptors, and Illustrators" },
  { role: "Special Effects Artists and Animators" },
  { role: "Artists and Related Workers, All Other" },
  { role: "Designers" },
  { role: "Commercial and Industrial Designers" },
  { role: "Fashion Designers" },
  { role: "Floral Designers" },
  { role: "Graphic Designers" },
  { role: "Interior Designers" },
  { role: "Merchandise Displayers and Window Trimmers" },
  { role: "Set and Exhibit Designers" },
  { role: "Designers, All Other" },
  { role: "Actors, Producers, and Directors" },
  { role: "Actors" },
  { role: "Producers and Directors" },
  { role: "Athletes, Coaches, Umpires, and Related Workers" },
  { role: "Athletes and Sports Competitors" },
  { role: "Coaches and Scouts" },
  { role: "Umpires, Referees, and Other Sports Officials" },
  { role: "Dancers and Choreographers" },
  { role: "Dancers" },
  { role: "Choreographers" },
  { role: "Musicians, Singers, and Related Workers" },
  { role: "Music Directors and Composers" },
  { role: "Musicians and Singers" },
  {
    role:
      "Miscellaneous Entertainers and Performers, Sports and Related Workers",
  },
  { role: "Disc Jockeys, Except Radio" },
  {
    role: "Entertainers and Performers, Sports and Related Workers, All Other",
  },
  { role: "Broadcast Announcers and Radio Disc Jockeys" },
  { role: "News Analysts, Reporters and Journalists" },
  { role: "News Analysts, Reporters, and Journalists" },
  { role: "Public Relations Specialists" },
  { role: "Writers and Editors" },
  { role: "Editors" },
  { role: "Technical Writers" },
  { role: "Writers and Authors" },
  { role: "Miscellaneous Media and Communication Workers" },
  { role: "Interpreters and Translators" },
  { role: "Court Reporters and Simultaneous Captioners" },
  { role: "Media and Communication Workers, All Other" },
  { role: "Broadcast, Sound, and Lighting Technicians" },
  { role: "Audio and Video Technicians" },
  { role: "Broadcast Technicians" },
  { role: "Sound Engineering Technicians" },
  { role: "Lighting Technicians" },
  { role: "Photographers" },
  { role: "Television, Video, and Film Camera Operators and Editors" },
  { role: "Camera Operators, Television, Video, and Film" },
  { role: "Film and Video Editors" },
  { role: "Miscellaneous Media and Communication Equipment Workers" },
  { role: "Media and Communication Equipment Workers, All Other" },
  { role: "Chiropractors" },
  { role: "Dentists" },
  { role: "Dentists, General" },
  { role: "Oral and Maxillofacial Surgeons" },
  { role: "Orthodontists" },
  { role: "Prosthodontists" },
  { role: "Dentists, All Other Specialists" },
  { role: "Dietitians and Nutritionists" },
  { role: "Optometrists" },
  { role: "Pharmacists" },
  { role: "Physician Assistants" },
  { role: "Podiatrists" },
  { role: "Therapists" },
  { role: "Occupational Therapists" },
  { role: "Physical Therapists" },
  { role: "Radiation Therapists" },
  { role: "Recreational Therapists" },
  { role: "Respiratory Therapists" },
  { role: "Speech-Language Pathologists" },
  { role: "Exercise Physiologists" },
  { role: "Therapists, All Other" },
  { role: "Veterinarians" },
  { role: "Registered Nurses" },
  { role: "Nurse Anesthetists" },
  { role: "Nurse Midwives" },
  { role: "Nurse Practitioners" },
  { role: "Audiologists" },
  { role: "Physicians" },
  { role: "Anesthesiologists" },
  { role: "Cardiologists" },
  { role: "Dermatologists" },
  { role: "Emergency Medicine Physicians" },
  { role: "Family Medicine Physicians" },
  { role: "General Internal Medicine Physicians" },
  { role: "Neurologists" },
  { role: "Obstetricians and Gynecologists" },
  { role: "Pediatricians, General" },
  { role: "Physicians, Pathologists" },
  { role: "Psychiatrists" },
  { role: "Radiologists" },
  { role: "Physicians, All Other" },
  { role: "Surgeons" },
  { role: "Ophthalmologists, Except Pediatric" },
  { role: "Orthopedic Surgeons, Except Pediatric" },
  { role: "Pediatric Surgeons" },
  { role: "Surgeons, All Other" },
  { role: "Miscellaneous Healthcare Diagnosing or Treating Practitioners" },
  { role: "Acupuncturists" },
  { role: "Dental Hygienists" },
  { role: "Healthcare Diagnosing or Treating Practitioners, All Other" },
  { role: "Clinical Laboratory Technologists and Technicians" },
  { role: "Medical and Clinical Laboratory Technologists" },
  { role: "Medical and Clinical Laboratory Technicians" },
  { role: "Diagnostic Related Technologists and Technicians" },
  { role: "Cardiovascular Technologists and Technicians" },
  { role: "Diagnostic Medical Sonographers" },
  { role: "Nuclear Medicine Technologists" },
  { role: "Radiologic Technologists and Technicians" },
  { role: "Magnetic Resonance Imaging Technologists" },
  { role: "Medical Dosimetrists" },
  { role: "Emergency Medical Technicians and Paramedics" },
  { role: "Emergency Medical Technicians" },
  { role: "Paramedics" },
  { role: "Health Practitioner Support Technologists and Technicians" },
  { role: "Dietetic Technicians" },
  { role: "Pharmacy Technicians" },
  { role: "Psychiatric Technicians" },
  { role: "Surgical Technologists" },
  { role: "Veterinary Technologists and Technicians" },
  { role: "Ophthalmic Medical Technicians" },
  { role: "Licensed Practical and Licensed Vocational Nurses" },
  { role: "Medical Records Specialists" },
  { role: "Opticians, Dispensing" },
  { role: "Miscellaneous Health Technologists and Technicians" },
  { role: "Orthotists and Prosthetists" },
  { role: "Hearing Aid Specialists" },
  { role: "Health Technologists and Technicians, All Other" },
  { role: "Health Information Technologists and Medical Registrars" },
  { role: "Miscellaneous Health Practitioners and Technical Workers" },
  { role: "Athletic Trainers" },
  { role: "Genetic Counselors" },
  { role: "Surgical Assistants" },
  { role: "Healthcare Practitioners and Technical Workers, All Other" },
  { role: "Home Health and Personal Care Aides" },
  { role: "Home Health Aides" },
  { role: "Personal Care Aides" },
  { role: "Nursing Assistants, Orderlies, and Psychiatric Aides" },
  { role: "Nursing Assistants" },
  { role: "Orderlies" },
  { role: "Psychiatric Aides" },
  { role: "Occupational Therapy Assistants and Aides" },
  { role: "Occupational Therapy Assistants" },
  { role: "Occupational Therapy Aides" },
  { role: "Physical Therapist Assistants and Aides" },
  { role: "Physical Therapist Assistants" },
  { role: "Physical Therapist Aides" },
  { role: "Massage Therapists" },
  { role: "Miscellaneous Healthcare Support Occupations" },
  { role: "Dental Assistants" },
  { role: "Medical Assistants" },
  { role: "Medical Equipment Preparers" },
  { role: "Medical Transcriptionists" },
  { role: "Pharmacy Aides" },
  { role: "Veterinary Assistants and Laboratory Animal Caretakers" },
  { role: "Phlebotomists" },
  { role: "Healthcare Support Workers, All Other" },
  { role: "First-Line Supervisors of Law Enforcement Workers" },
  { role: "First-Line Supervisors of Correctional Officers" },
  { role: "First-Line Supervisors of Police and Detectives" },
  { role: "First-Line Supervisors of Firefighting and Prevention Workers" },
  { role: "Miscellaneous First-Line Supervisors, Protective Service Workers" },
  { role: "First-Line Supervisors of Security Workers" },
  { role: "First-Line Supervisors of Protective Service Workers, All Other" },
  { role: "Firefighters" },
  { role: "Fire Inspectors" },
  { role: "Fire Inspectors and Investigators" },
  { role: "Forest Fire Inspectors and Prevention Specialists" },
  { role: "Bailiffs, Correctional Officers, and Jailers" },
  { role: "Bailiffs" },
  { role: "Correctional Officers and Jailers" },
  { role: "Detectives and Criminal Investigators" },
  { role: "Fish and Game Wardens" },
  { role: "Parking Enforcement Workers" },
  { role: "Police Officers" },
  { role: "Police and Sheriff\u2019s Patrol Officers" },
  { role: "Transit and Railroad Police" },
  { role: "Animal Control Workers" },
  { role: "Private Detectives and Investigators" },
  { role: "Security Guards and Gambling Surveillance Officers" },
  { role: "Gambling Surveillance Officers and Gambling Investigators" },
  { role: "Security Guards" },
  { role: "Miscellaneous Protective Service Workers" },
  { role: "Crossing Guards and Flaggers" },
  {
    role:
      "Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers",
  },
  { role: "Transportation Security Screeners" },
  { role: "School Bus Monitors" },
  { role: "Protective Service Workers, All Other" },
  { role: "Supervisors of Food Preparation and Serving Workers" },
  { role: "Chefs and Head Cooks" },
  { role: "First-Line Supervisors of Food Preparation and Serving Workers" },
  { role: "Cooks" },
  { role: "Cooks, Fast Food" },
  { role: "Cooks, Institution and Cafeteria" },
  { role: "Cooks, Private Household" },
  { role: "Cooks, Restaurant" },
  { role: "Cooks, Short Order" },
  { role: "Cooks, All Other" },
  { role: "Food Preparation Workers" },
  { role: "Bartenders" },
  { role: "Fast Food and Counter Workers" },
  { role: "Waiters and Waitresses" },
  { role: "Food Servers, Nonrestaurant" },
  { role: "Dining Room and Cafeteria Attendants and Bartender Helpers" },
  { role: "Dishwashers" },
  { role: "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop" },
  { role: "Miscellaneous Food Preparation and Serving Related Workers" },
  { role: "Food Preparation and Serving Related Workers, All Other" },
  {
    role:
      "First-Line Supervisors of Building and Grounds Cleaning and Maintenance Workers",
  },
  { role: "First-Line Supervisors of Housekeeping and Janitorial Workers" },
  {
    role:
      "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers",
  },
  { role: "Building Cleaning Workers" },
  { role: "Janitors and Cleaners, Except Maids and Housekeeping Cleaners" },
  { role: "Maids and Housekeeping Cleaners" },
  { role: "Building Cleaning Workers, All Other" },
  { role: "Pest Control Workers" },
  { role: "Grounds Maintenance Workers" },
  { role: "Landscaping and Groundskeeping Workers" },
  { role: "Pesticide Handlers, Sprayers, and Applicators, Vegetation" },
  { role: "Tree Trimmers and Pruners" },
  { role: "Grounds Maintenance Workers, All Other" },
  { role: "First-Line Supervisors of Entertainment and Recreation Workers" },
  { role: "First-Line Supervisors of Gambling Services Workers" },
  {
    role:
      "First-Line Supervisors of Entertainment and Recreation Workers, Except Gambling Services",
  },
  { role: "First-Line Supervisors of Personal Service Workers" },
  { role: "Animal Trainers" },
  { role: "Animal Caretakers" },
  { role: "Gambling Services Workers" },
  { role: "Gambling Dealers" },
  { role: "Gambling and Sports Book Writers and Runners" },
  { role: "Gambling Service Workers, All Other" },
  { role: "Motion Picture Projectionists" },
  { role: "Ushers, Lobby Attendants, and Ticket Takers" },
  { role: "Miscellaneous Entertainment Attendants and Related Workers" },
  { role: "Amusement and Recreation Attendants" },
  { role: "Costume Attendants" },
  { role: "Locker Room, Coatroom, and Dressing Room Attendants" },
  { role: "Entertainment Attendants and Related Workers, All Other" },
  { role: "Embalmers and Crematory Operators" },
  { role: "Embalmers" },
  { role: "Crematory Operators" },
  { role: "Funeral Attendants" },
  { role: "Morticians, Undertakers, and Funeral Arrangers" },
  { role: "Barbers, Hairdressers, Hairstylists and Cosmetologists" },
  { role: "Barbers" },
  { role: "Hairdressers, Hairstylists, and Cosmetologists" },
  { role: "Miscellaneous Personal Appearance Workers" },
  { role: "Makeup Artists, Theatrical and Performance" },
  { role: "Manicurists and Pedicurists" },
  { role: "Shampooers" },
  { role: "Skincare Specialists" },
  { role: "Baggage Porters, Bellhops, and Concierges" },
  { role: "Baggage Porters and Bellhops" },
  { role: "Concierges" },
  { role: "Tour and Travel Guides" },
  { role: "Tour Guides and Escorts" },
  { role: "Travel Guides" },
  { role: "Childcare Workers" },
  { role: "Recreation and Fitness Workers" },
  { role: "Exercise Trainers and Group Fitness Instructors" },
  { role: "Recreation Workers" },
  { role: "Residential Advisors" },
  { role: "Miscellaneous Personal Care and Service Workers" },
  { role: "Personal Care and Service Workers, All Other" },
  { role: "First-Line Supervisors of Sales Workers" },
  { role: "First-Line Supervisors of Retail Sales Workers" },
  { role: "First-Line Supervisors of Non-Retail Sales Workers" },
  { role: "Cashiers" },
  { role: "Gambling Change Persons and Booth Cashiers" },
  { role: "Counter and Rental Clerks and Parts Salespersons" },
  { role: "Counter and Rental Clerks" },
  { role: "Parts Salespersons" },
  { role: "Retail Salespersons" },
  { role: "Advertising Sales Agents" },
  { role: "Insurance Sales Agents" },
  { role: "Securities, Commodities, and Financial Services Sales Agents" },
  { role: "Travel Agents" },
  { role: "Miscellaneous Sales Representatives, Services" },
  {
    role:
      "Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel",
  },
  { role: "Sales Representatives, Wholesale and Manufacturing" },
  {
    role:
      "Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products",
  },
  {
    role:
      "Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products",
  },
  { role: "Models, Demonstrators, and Product Promoters" },
  { role: "Demonstrators and Product Promoters" },
  { role: "Models" },
  { role: "Real Estate Brokers and Sales Agents" },
  { role: "Real Estate Brokers" },
  { role: "Real Estate Sales Agents" },
  { role: "Sales Engineers" },
  { role: "Telemarketers" },
  { role: "Miscellaneous Sales and Related Workers" },
  {
    role:
      "Door-to-Door Sales Workers, News and Street Vendors, and Related Workers",
  },
  { role: "Sales and Related Workers, All Other" },
  {
    role: "First-Line Supervisors of Office and Administrative Support Workers",
  },
  { role: "Switchboard Operators, Including Answering Service" },
  { role: "Telephone Operators" },
  { role: "Miscellaneous Communications Equipment Operators" },
  { role: "Communications Equipment Operators, All Other" },
  { role: "Bill and Account Collectors" },
  { role: "Billing and Posting Clerks" },
  { role: "Bookkeeping, Accounting, and Auditing Clerks" },
  { role: "Gambling Cage Workers" },
  { role: "Payroll and Timekeeping Clerks" },
  { role: "Procurement Clerks" },
  { role: "Tellers" },
  { role: "Miscellaneous Financial Clerks" },
  { role: "Financial Clerks, All Other" },
  { role: "Brokerage Clerks" },
  { role: "Correspondence Clerks" },
  { role: "Court, Municipal, and License Clerks" },
  { role: "Credit Authorizers, Checkers, and Clerks" },
  { role: "Customer Service Representatives" },
  { role: "Eligibility Interviewers, Government Programs" },
  { role: "File Clerks" },
  { role: "Hotel, Motel, and Resort Desk Clerks" },
  { role: "Interviewers, Except Eligibility and Loan" },
  { role: "Library Assistants, Clerical" },
  { role: "Loan Interviewers and Clerks" },
  { role: "New Accounts Clerks" },
  { role: "Order Clerks" },
  { role: "Human Resources Assistants, Except Payroll and Timekeeping" },
  { role: "Receptionists and Information Clerks" },
  { role: "Reservation and Transportation Ticket Agents and Travel Clerks" },
  { role: "Miscellaneous Information and Record Clerks" },
  { role: "Information and Record Clerks, All Other" },
  { role: "Cargo and Freight Agents" },
  { role: "Couriers and Messengers" },
  { role: "Dispatchers" },
  { role: "Public Safety Telecommunicators" },
  { role: "Dispatchers, Except Police, Fire, and Ambulance" },
  { role: "Meter Readers, Utilities" },
  { role: "Postal Service Workers" },
  { role: "Postal Service Clerks" },
  { role: "Postal Service Mail Carriers" },
  {
    role:
      "Postal Service Mail Sorters, Processors, and Processing Machine Operators",
  },
  { role: "Production, Planning, and Expediting Clerks" },
  { role: "Shipping, Receiving, and Inventory Clerks" },
  { role: "Weighers, Measurers, Checkers, and Samplers, Recordkeeping" },
  { role: "Secretaries and Administrative Assistants" },
  { role: "Executive Secretaries and Executive Administrative Assistants" },
  { role: "Legal Secretaries and Administrative Assistants" },
  { role: "Medical Secretaries and Administrative Assistants" },
  {
    role:
      "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
  },
  { role: "Data Entry and Information Processing Workers" },
  { role: "Data Entry Keyers" },
  { role: "Word Processors and Typists" },
  { role: "Desktop Publishers" },
  { role: "Insurance Claims and Policy Processing Clerks" },
  { role: "Mail Clerks and Mail Machine Operators, Except Postal Service" },
  { role: "Office Clerks, General" },
  { role: "Office Machine Operators, Except Computer" },
  { role: "Proofreaders and Copy Markers" },
  { role: "Statistical Assistants" },
  { role: "Miscellaneous Office and Administrative Support Workers" },
  { role: "Office and Administrative Support Workers, All Other" },
  { role: "First-Line Supervisors of Farming, Fishing, and Forestry Workers" },
  { role: "Agricultural Inspectors" },
  { role: "Animal Breeders" },
  { role: "Graders and Sorters, Agricultural Products" },
  { role: "Miscellaneous Agricultural Workers" },
  { role: "Agricultural Equipment Operators" },
  { role: "Farmworkers and Laborers, Crop, Nursery, and Greenhouse" },
  { role: "Farmworkers, Farm, Ranch, and Aquacultural Animals" },
  { role: "Agricultural Workers, All Other" },
  { role: "Fishing and Hunting Workers" },
  { role: "Forest and Conservation Workers" },
  { role: "Logging Workers" },
  { role: "Fallers" },
  { role: "Logging Equipment Operators" },
  { role: "Log Graders and Scalers" },
  { role: "Logging Workers, All Other" },
  {
    role:
      "First-Line Supervisors of Construction Trades and Extraction Workers",
  },
  { role: "Boilermakers" },
  { role: "Brickmasons, Blockmasons, and Stonemasons" },
  { role: "Brickmasons and Blockmasons" },
  { role: "Stonemasons" },
  { role: "Carpenters" },
  { role: "Carpet, Floor, and Tile Installers and Finishers" },
  { role: "Carpet Installers" },
  { role: "Floor Layers, Except Carpet, Wood, and Hard Tiles" },
  { role: "Floor Sanders and Finishers" },
  { role: "Tile and Stone Setters" },
  { role: "Cement Masons, Concrete Finishers, and Terrazzo Workers" },
  { role: "Cement Masons and Concrete Finishers" },
  { role: "Terrazzo Workers and Finishers" },
  { role: "Construction Laborers" },
  { role: "Construction Equipment Operators" },
  { role: "Paving, Surfacing, and Tamping Equipment Operators" },
  { role: "Pile Driver Operators" },
  { role: "Operating Engineers and Other Construction Equipment Operators" },
  { role: "Drywall Installers, Ceiling Tile Installers, and Tapers" },
  { role: "Drywall and Ceiling Tile Installers" },
  { role: "Tapers" },
  { role: "Electricians" },
  { role: "Glaziers" },
  { role: "Insulation Workers" },
  { role: "Insulation Workers, Floor, Ceiling, and Wall" },
  { role: "Insulation Workers, Mechanical" },
  { role: "Painters and Paperhangers" },
  { role: "Painters, Construction and Maintenance" },
  { role: "Paperhangers" },
  { role: "Pipelayers, Plumbers, Pipefitters, and Steamfitters" },
  { role: "Pipelayers" },
  { role: "Plumbers, Pipefitters, and Steamfitters" },
  { role: "Plasterers and Stucco Masons" },
  { role: "Reinforcing Iron and Rebar Workers" },
  { role: "Roofers" },
  { role: "Sheet Metal Workers" },
  { role: "Structural Iron and Steel Workers" },
  { role: "Solar Photovoltaic Installers" },
  { role: "Helpers, Construction Trades" },
  {
    role:
      "Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters",
  },
  { role: "Helpers--Carpenters" },
  { role: "Helpers--Electricians" },
  { role: "Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons" },
  { role: "Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters" },
  { role: "Helpers--Roofers" },
  { role: "Helpers, Construction Trades, All Other" },
  { role: "Construction and Building Inspectors" },
  { role: "Elevator and Escalator Installers and Repairers" },
  { role: "Fence Erectors" },
  { role: "Hazardous Materials Removal Workers" },
  { role: "Highway Maintenance Workers" },
  { role: "Rail-Track Laying and Maintenance Equipment Operators" },
  { role: "Septic Tank Servicers and Sewer Pipe Cleaners" },
  { role: "Miscellaneous Construction and Related Workers" },
  { role: "Segmental Pavers" },
  { role: "Construction and Related Workers, All Other" },
  { role: "Derrick, Rotary Drill, and Service Unit Operators, Oil and Gas" },
  { role: "Derrick Operators, Oil and Gas" },
  { role: "Rotary Drill Operators, Oil and Gas" },
  { role: "Service Unit Operators, Oil and Gas" },
  { role: "Surface Mining Machine Operators and Earth Drillers" },
  {
    role:
      "Excavating and Loading Machine and Dragline Operators, Surface Mining",
  },
  { role: "Earth Drillers, Except Oil and Gas" },
  { role: "Explosives Workers, Ordnance Handling Experts, and Blasters" },
  { role: "Underground Mining Machine Operators" },
  { role: "Continuous Mining Machine Operators" },
  { role: "Roof Bolters, Mining" },
  { role: "Loading and Moving Machine Operators, Underground Mining" },
  { role: "Underground Mining Machine Operators, All Other" },
  { role: "Rock Splitters, Quarry" },
  { role: "Roustabouts, Oil and Gas" },
  { role: "Helpers--Extraction Workers" },
  { role: "Miscellaneous Extraction Workers" },
  { role: "Extraction Workers, All Other" },
  { role: "First-Line Supervisors of Mechanics, Installers, and Repairers" },
  { role: "Computer, Automated Teller, and Office Machine Repairers" },
  { role: "Radio and Telecommunications Equipment Installers and Repairers" },
  { role: "Radio, Cellular, and Tower Equipment Installers and Repairers" },
  {
    role:
      "Telecommunications Equipment Installers and Repairers, Except Line Installers",
  },
  {
    role:
      "Miscellaneous Electrical and Electronic Equipment Mechanics, Installers, and Repairers",
  },
  { role: "Avionics Technicians" },
  { role: "Electric Motor, Power Tool, and Related Repairers" },
  {
    role:
      "Electrical and Electronics Installers and Repairers, Transportation Equipment",
  },
  {
    role:
      "Electrical and Electronics Repairers, Commercial and Industrial Equipment",
  },
  {
    role:
      "Electrical and Electronics Repairers, Powerhouse, Substation, and Relay",
  },
  { role: "Electronic Equipment Installers and Repairers, Motor Vehicles" },
  { role: "Audiovisual Equipment Installers and Repairers" },
  { role: "Security and Fire Alarm Systems Installers" },
  { role: "Aircraft Mechanics and Service Technicians" },
  { role: "Automotive Technicians and Repairers" },
  { role: "Automotive Body and Related Repairers" },
  { role: "Automotive Glass Installers and Repairers" },
  { role: "Automotive Service Technicians and Mechanics" },
  { role: "Bus and Truck Mechanics and Diesel Engine Specialists" },
  {
    role:
      "Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics",
  },
  { role: "Farm Equipment Mechanics and Service Technicians" },
  { role: "Mobile Heavy Equipment Mechanics, Except Engines" },
  { role: "Rail Car Repairers" },
  { role: "Small Engine Mechanics" },
  { role: "Motorboat Mechanics and Service Technicians" },
  { role: "Motorcycle Mechanics" },
  { role: "Outdoor Power Equipment and Other Small Engine Mechanics" },
  {
    role:
      "Miscellaneous Vehicle and Mobile Equipment Mechanics, Installers, and Repairers",
  },
  { role: "Bicycle Repairers" },
  { role: "Recreational Vehicle Service Technicians" },
  { role: "Tire Repairers and Changers" },
  { role: "Control and Valve Installers and Repairers" },
  { role: "Mechanical Door Repairers" },
  {
    role: "Control and Valve Installers and Repairers, Except Mechanical Door",
  },
  {
    role:
      "Heating, Air Conditioning, and Refrigeration Mechanics and Installers",
  },
  { role: "Home Appliance Repairers" },
  {
    role: "Industrial Machinery Installation, Repair, and Maintenance Workers",
  },
  { role: "Industrial Machinery Mechanics" },
  { role: "Maintenance Workers, Machinery" },
  { role: "Millwrights" },
  { role: "Refractory Materials Repairers, Except Brickmasons" },
  { role: "Line Installers and Repairers" },
  { role: "Electrical Power-Line Installers and Repairers" },
  { role: "Telecommunications Line Installers and Repairers" },
  { role: "Precision Instrument and Equipment Repairers" },
  { role: "Camera and Photographic Equipment Repairers" },
  { role: "Medical Equipment Repairers" },
  { role: "Musical Instrument Repairers and Tuners" },
  { role: "Watch and Clock Repairers" },
  { role: "Precision Instrument and Equipment Repairers, All Other" },
  { role: "Maintenance and Repair Workers, General" },
  { role: "Wind Turbine Service Technicians" },
  { role: "Miscellaneous Installation, Maintenance, and Repair Workers" },
  { role: "Coin, Vending, and Amusement Machine Servicers and Repairers" },
  { role: "Commercial Divers" },
  { role: "Locksmiths and Safe Repairers" },
  { role: "Manufactured Building and Mobile Home Installers" },
  { role: "Riggers" },
  { role: "Signal and Track Switch Repairers" },
  { role: "Helpers--Installation, Maintenance, and Repair Workers" },
  { role: "Installation, Maintenance, and Repair Workers, All Other" },
  { role: "First-Line Supervisors of Production and Operating Workers" },
  { role: "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers" },
  { role: "Electrical, Electronics, and Electromechanical Assemblers" },
  { role: "Coil Winders, Tapers, and Finishers" },
  { role: "Electrical and Electronic Equipment Assemblers" },
  { role: "Electromechanical Equipment Assemblers" },
  { role: "Engine and Other Machine Assemblers" },
  { role: "Structural Metal Fabricators and Fitters" },
  { role: "Fiberglass Laminators and Fabricators" },
  { role: "Timing Device Assemblers and Adjusters" },
  { role: "Miscellaneous Assemblers and Fabricators" },
  { role: "Team Assemblers" },
  { role: "Assemblers and Fabricators, All Other" },
  { role: "Bakers" },
  { role: "Butchers and Other Meat, Poultry, and Fish Processing Workers" },
  { role: "Butchers and Meat Cutters" },
  { role: "Meat, Poultry, and Fish Cutters and Trimmers" },
  { role: "Slaughterers and Meat Packers" },
  { role: "Miscellaneous Food Processing Workers" },
  {
    role:
      "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders",
  },
  { role: "Food Batchmakers" },
  { role: "Food Cooking Machine Operators and Tenders" },
  { role: "Food Processing Workers, All Other" },
  {
    role: "Forming Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role: "Forging Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role: "Rolling Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Machine Tool Cutting Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  { role: "Machinists" },
  { role: "Metal Furnace Operators, Tenders, Pourers, and Casters" },
  { role: "Metal-Refining Furnace Operators and Tenders" },
  { role: "Pourers and Casters, Metal" },
  { role: "Model Makers and Patternmakers, Metal and Plastic" },
  { role: "Model Makers, Metal and Plastic" },
  { role: "Patternmakers, Metal and Plastic" },
  {
    role:
      "Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  { role: "Foundry Mold and Coremakers" },
  {
    role:
      "Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  {
    role:
      "Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
  },
  { role: "Tool and Die Makers" },
  { role: "Welding, Soldering, and Brazing Workers" },
  { role: "Welders, Cutters, Solderers, and Brazers" },
  {
    role:
      "Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders",
  },
  { role: "Miscellaneous Metal Workers and Plastic Workers" },
  {
    role:
      "Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic",
  },
  { role: "Layout Workers, Metal and Plastic" },
  {
    role: "Plating Machine Setters, Operators, and Tenders, Metal and Plastic",
  },
  { role: "Tool Grinders, Filers, and Sharpeners" },
  { role: "Metal Workers and Plastic Workers, All Other" },
  { role: "Printing Workers" },
  { role: "Prepress Technicians and Workers" },
  { role: "Printing Press Operators" },
  { role: "Print Binding and Finishing Workers" },
  { role: "Laundry and Dry-Cleaning Workers" },
  { role: "Pressers, Textile, Garment, and Related Materials" },
  { role: "Sewing Machine Operators" },
  { role: "Shoe and Leather Workers" },
  { role: "Shoe and Leather Workers and Repairers" },
  { role: "Shoe Machine Operators and Tenders" },
  { role: "Tailors, Dressmakers, and Sewers" },
  { role: "Sewers, Hand" },
  { role: "Tailors, Dressmakers, and Custom Sewers" },
  { role: "Textile Machine Setters, Operators, and Tenders" },
  { role: "Textile Bleaching and Dyeing Machine Operators and Tenders" },
  { role: "Textile Cutting Machine Setters, Operators, and Tenders" },
  {
    role:
      "Textile Knitting and Weaving Machine Setters, Operators, and Tenders",
  },
  {
    role:
      "Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders",
  },
  { role: "Miscellaneous Textile, Apparel, and Furnishings Workers" },
  {
    role:
      "Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers",
  },
  { role: "Fabric and Apparel Patternmakers" },
  { role: "Upholsterers" },
  { role: "Textile, Apparel, and Furnishings Workers, All Other" },
  { role: "Cabinetmakers and Bench Carpenters" },
  { role: "Furniture Finishers" },
  { role: "Model Makers and Patternmakers, Wood" },
  { role: "Model Makers, Wood" },
  { role: "Patternmakers, Wood" },
  { role: "Woodworking Machine Setters, Operators, and Tenders" },
  { role: "Sawing Machine Setters, Operators, and Tenders, Wood" },
  {
    role: "Woodworking Machine Setters, Operators, and Tenders, Except Sawing",
  },
  { role: "Miscellaneous Woodworkers" },
  { role: "Woodworkers, All Other" },
  { role: "Power Plant Operators, Distributors, and Dispatchers" },
  { role: "Nuclear Power Reactor Operators" },
  { role: "Power Distributors and Dispatchers" },
  { role: "Power Plant Operators" },
  { role: "Stationary Engineers and Boiler Operators" },
  { role: "Water and Wastewater Treatment Plant and System Operators" },
  { role: "Miscellaneous Plant and System Operators" },
  { role: "Chemical Plant and System Operators" },
  { role: "Gas Plant Operators" },
  { role: "Petroleum Pump System Operators, Refinery Operators, and Gaugers" },
  { role: "Plant and System Operators, All Other" },
  { role: "Chemical Processing Machine Setters, Operators, and Tenders" },
  { role: "Chemical Equipment Operators and Tenders" },
  {
    role:
      "Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders",
  },
  { role: "Crushing, Grinding, Polishing, Mixing, and Blending Workers" },
  {
    role:
      "Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders",
  },
  { role: "Grinding and Polishing Workers, Hand" },
  { role: "Mixing and Blending Machine Setters, Operators, and Tenders" },
  { role: "Cutting Workers" },
  { role: "Cutters and Trimmers, Hand" },
  { role: "Cutting and Slicing Machine Setters, Operators, and Tenders" },
  {
    role:
      "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders",
  },
  { role: "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders" },
  { role: "Inspectors, Testers, Sorters, Samplers, and Weighers" },
  { role: "Jewelers and Precious Stone and Metal Workers" },
  {
    role:
      "Dental and Ophthalmic Laboratory Technicians and Medical Appliance Technicians",
  },
  { role: "Dental Laboratory Technicians" },
  { role: "Medical Appliance Technicians" },
  { role: "Ophthalmic Laboratory Technicians" },
  { role: "Packaging and Filling Machine Operators and Tenders" },
  { role: "Painting Workers" },
  { role: "Painting, Coating, and Decorating Workers" },
  {
    role:
      "Coating, Painting, and Spraying Machine Setters, Operators, and Tenders",
  },
  { role: "Semiconductor Processing Technicians" },
  { role: "Photographic Process Workers and Processing Machine Operators" },
  { role: "Computer Numerically Controlled Tool Operators and Programmers" },
  { role: "Computer Numerically Controlled Tool Operators" },
  { role: "Computer Numerically Controlled Tool Programmers" },
  { role: "Miscellaneous Production Workers" },
  { role: "Adhesive Bonding Machine Operators and Tenders" },
  {
    role:
      "Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders",
  },
  { role: "Cooling and Freezing Equipment Operators and Tenders" },
  { role: "Etchers and Engravers" },
  { role: "Molders, Shapers, and Casters, Except Metal and Plastic" },
  { role: "Paper Goods Machine Setters, Operators, and Tenders" },
  { role: "Tire Builders" },
  { role: "Helpers--Production Workers" },
  { role: "Production Workers, All Other" },
  {
    role:
      "First-Line Supervisors of Transportation and Material Moving Workers",
  },
  { role: "Aircraft Cargo Handling Supervisors" },
  {
    role:
      "First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand",
  },
  {
    role:
      "First-Line Supervisors of Material-Moving Machine and Vehicle Operators",
  },
  { role: "First-Line Supervisors of Passenger Attendants" },
  { role: "First-Line Supervisors of Transportation Workers, All Other" },
  { role: "Aircraft Pilots and Flight Engineers" },
  { role: "Airline Pilots, Copilots, and Flight Engineers" },
  { role: "Commercial Pilots" },
  { role: "Air Traffic Controllers and Airfield Operations Specialists" },
  { role: "Air Traffic Controllers" },
  { role: "Airfield Operations Specialists" },
  { role: "Flight Attendants" },
  {
    role:
      "Ambulance Drivers and Attendants, Except Emergency Medical Technicians",
  },
  { role: "Driver/Sales Workers and Truck Drivers" },
  { role: "Driver/Sales Workers" },
  { role: "Heavy and Tractor-Trailer Truck Drivers" },
  { role: "Light Truck Drivers" },
  { role: "Passenger Vehicle Drivers" },
  { role: "Bus Drivers, School" },
  { role: "Bus Drivers, Transit and Intercity" },
  { role: "Shuttle Drivers and Chauffeurs" },
  { role: "Taxi Drivers" },
  { role: "Miscellaneous Motor Vehicle Operators" },
  { role: "Motor Vehicle Operators, All Other" },
  { role: "Locomotive Engineers and Operators" },
  { role: "Locomotive Engineers" },
  { role: "Rail Yard Engineers, Dinkey Operators, and Hostlers" },
  {
    role: "Railroad Brake, Signal, and Switch Operators and Locomotive Firers",
  },
  { role: "Railroad Conductors and Yardmasters" },
  { role: "Subway and Streetcar Operators" },
  { role: "Miscellaneous Rail Transportation Workers" },
  { role: "Rail Transportation Workers, All Other" },
  { role: "Sailors and Marine Oilers" },
  { role: "Ship and Boat Captains and Operators" },
  { role: "Captains, Mates, and Pilots of Water Vessels" },
  { role: "Motorboat Operators" },
  { role: "Ship Engineers" },
  { role: "Bridge and Lock Tenders" },
  { role: "Parking Attendants" },
  { role: "Transportation Service Attendants" },
  { role: "Automotive and Watercraft Service Attendants" },
  { role: "Aircraft Service Attendants" },
  { role: "Traffic Technicians" },
  { role: "Transportation Inspectors" },
  { role: "Passenger Attendants" },
  { role: "Miscellaneous Transportation Workers" },
  { role: "Transportation Workers, All Other" },
  { role: "Conveyor Operators and Tenders" },
  { role: "Crane and Tower Operators" },
  { role: "Dredge Operators" },
  { role: "Hoist and Winch Operators" },
  { role: "Industrial Truck and Tractor Operators" },
  { role: "Laborers and Material Movers" },
  { role: "Cleaners of Vehicles and Equipment" },
  { role: "Laborers and Freight, Stock, and Material Movers, Hand" },
  { role: "Machine Feeders and Offbearers" },
  { role: "Packers and Packagers, Hand" },
  { role: "Stockers and Order Fillers" },
  { role: "Pumping Station Operators" },
  { role: "Gas Compressor and Gas Pumping Station Operators" },
  { role: "Pump Operators, Except Wellhead Pumpers" },
  { role: "Wellhead Pumpers" },
  { role: "Refuse and Recyclable Material Collectors" },
  { role: "Tank Car, Truck, and Ship Loaders" },
  { role: "Miscellaneous Material Moving Workers" },
  { role: "Material Moving Workers, All Other" },
  { role: "Military Officer Special and Tactical Operations Leaders" },
  { role: "Air Crew Officers" },
  { role: "Aircraft Launch and Recovery Officers" },
  { role: "Armored Assault Vehicle Officers" },
  { role: "Artillery and Missile Officers" },
  { role: "Command and Control Center Officers" },
  { role: "Infantry Officers" },
  { role: "Special Forces Officers" },
  {
    role: "Military Officer Special and Tactical Operations Leaders, All Other",
  },
  { role: "First-Line Enlisted Military Supervisors" },
  { role: "First-Line Supervisors of Air Crew Members" },
  { role: "First-Line Supervisors of Weapons Specialists/Crew Members" },
  {
    role: "First-Line Supervisors of All Other Tactical Operations Specialists",
  },
  {
    role:
      "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members",
  },
  { role: "Air Crew Members" },
  { role: "Aircraft Launch and Recovery Specialists" },
  { role: "Armored Assault Vehicle Crew Members" },
  { role: "Artillery and Missile Crew Members" },
  { role: "Command and Control Center Specialists" },
  { role: "Infantry" },
  { role: "Special Forces" },
  {
    role:
      "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other",
  },
];
